### ISSUE TITLE
Carregar Mais (Blog)

### ISSUE THREAD

**Issue by BrenoMaia98** [BrenoMaia98/Humanus-Site-e-Painel#8]
Ao final da página existe um botão que iria chamar o endPoint do back-end para carregar as proximas 10 postagens.A resposta do back seria concatenada com o array de postagens atuais presentes no site.

**Comment by JohnnyBaptista** [comment]
Pode ser feito uma paginação em vez de carregar mais?
Assim não fica muita informação na página

**Comment by BrenoMaia98** [comment]
pode ser feito. só optei pelo botão abaixo por ser mais rapido e fácil de implementar por conta do tempo

**Comment by JohnnyBaptista** [comment]
Fique tranqs, vou pegar esse pra fazer. Feshow?

**Comment by BrenoMaia98** [comment]
okay
